/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hc.ltd;

import java.awt.Color;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author obuzietter
 */
public class room_reserve_form extends javax.swing.JFrame {

    /**
     * Creates new form room_reserve_form
     */
    public room_reserve_form() {
        initComponents();
        updateCombo();

    }
private void reset(){
    nameTF.setText("");
    phoneTF.setText("");
    idTF.setText("");
    
}
    private void updateCombo() {
        roomNoCombo.removeAllItems();//problem
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
            String sql = "SELECT * FROM rooms";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet result = stmt.executeQuery(sql);
            
            while (result.next()) {
                if (result.getInt("room_state") == 0) {
                    
                    roomNoCombo.addItem(result.getString("room_no"));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        amtTF = new javax.swing.JTextField();
        paymentCombo = new javax.swing.JComboBox<>();
        bookBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        display_table = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        roomNoCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        roomTypeTF = new javax.swing.JTextField();
        spinner = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Room Reserve");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Phone");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("ID Number");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("Room Type");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setText("Payment Method");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("No of Days");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel10.setText("Amount");

        nameTF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        phoneTF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        idTF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        amtTF.setEditable(false);
        amtTF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        paymentCombo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        paymentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Method", "M-PESA", "CASH" }));

        bookBtn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        bookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-in.png"))); // NOI18N
        bookBtn.setText("CHECK IN");
        bookBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bookBtn.setIconTextGap(6);
        bookBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bookBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        display_table.setFont(new java.awt.Font("Nimbus Sans", 1, 18)); // NOI18N
        display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Id Number", "Room No", "Room Type", "No Of Days", "Amount", "Payment Method"
            }
        ));
        display_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        display_table.setRowHeight(35);
        display_table.setRowMargin(5);
        display_table.setSelectionBackground(new java.awt.Color(0, 255, 255));
        display_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        display_table.setShowGrid(false);
        display_table.setShowHorizontalLines(true);
        display_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(display_table);
        if (display_table.getColumnModel().getColumnCount() > 0) {
            display_table.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-button.png"))); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        checkoutBtn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        checkoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check-out.png"))); // NOI18N
        checkoutBtn.setText("CHECK OUT");
        checkoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkoutBtn.setIconTextGap(6);
        checkoutBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        checkoutBtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        roomNoCombo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        roomNoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roomNoComboItemStateChanged(evt);
            }
        });
        roomNoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNoComboActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setText("Room No");

        roomTypeTF.setEditable(false);
        roomTypeTF.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        roomTypeTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roomTypeTFFocusGained(evt);
            }
        });
        roomTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeTFActionPerformed(evt);
            }
        });

        spinner.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(roomNoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)
                                                .addComponent(roomTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bookBtn)
                                                .addGap(88, 88, 88)
                                                .addComponent(checkoutBtn))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(102, 102, 102)
                                                .addComponent(jLabel10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)
                                                .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8)
                                            .addComponent(paymentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(100, 100, 100)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(116, 116, 116)
                                .addComponent(jLabel6))
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(paymentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        nameTF.getAccessibleContext().setAccessibleDescription("");
        phoneTF.getAccessibleContext().setAccessibleDescription("");
        idTF.getAccessibleContext().setAccessibleDescription("");
        amtTF.getAccessibleContext().setAccessibleDescription("");
        paymentCombo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Bookings> bookings() {
        ArrayList<Bookings> bookings = new ArrayList<>();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
            String sql = "SELECT * FROM bookings";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet result = stmt.executeQuery(sql);

            Bookings booking;
            while (result.next()) {
                booking = new Bookings(result.getString("name"), result.getString("phone"), result.getString("id_no"), result.getString("room_no"), result.getString("room_type"), result.getString("no_of_days"), result.getString("amount"), result.getString("payment_method"));
                bookings.add(booking);

            }

        } catch (Exception e) {
            System.out.print(e);
        }
        return bookings;
    }

    public void display_bookings() {
        ArrayList<Bookings> bookingRecords = bookings();
        DefaultTableModel model = (DefaultTableModel) display_table.getModel();
        model.setRowCount(0); // Clear all data from the table
        Object[] col = new Object[8];

//        for (int i = 0; i < bookingRecords.size(); i++) {
        for (int i = bookingRecords.size() - 1; i >= 0; i--) {

            col[0] = bookingRecords.get(i).getName();
            col[1] = bookingRecords.get(i).getPhone();
            col[2] = bookingRecords.get(i).getId();
            col[3] = bookingRecords.get(i).getEmail();
            col[4] = bookingRecords.get(i).getRoomType();
            col[5] = bookingRecords.get(i).getNoOfDays();
            col[6] = bookingRecords.get(i).getAmt();
            col[7] = bookingRecords.get(i).getPaymentMethod();
            model.addRow(col);

        }

    }


    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
            String sql = "INSERT INTO bookings (name, phone, id_no, room_no, room_type, no_of_days, amount, payment_method) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nameTF.getText());
            stmt.setString(2, phoneTF.getText());
            stmt.setString(3, idTF.getText());
            stmt.setObject(4, roomNoCombo.getSelectedItem());
            stmt.setString(5, roomTypeTF.getText());
            stmt.setObject(6, spinner.getValue());
            stmt.setString(7, amtTF.getText());
            stmt.setObject(8, paymentCombo.getSelectedItem());
            stmt.executeUpdate();

            //UPDATING THE ROOM STATUS UPON MAKING RESERVATION
            String updateStatus = "UPDATE rooms SET room_state = ? WHERE room_no = ?";
            PreparedStatement updateStmt = conn.prepareStatement(updateStatus);
            updateStmt.setInt(1, 1);
            updateStmt.setObject(2, roomNoCombo.getSelectedItem());
            updateStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "BOOKING SUCCESSFUL!");
            updateCombo();
            reset();

        } catch (Exception e) {
            System.out.print(e);
        }

    }//GEN-LAST:event_bookBtnActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        display_bookings();
    }//GEN-LAST:event_refreshActionPerformed

    private void roomNoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNoComboActionPerformed

    private void roomNoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roomNoComboItemStateChanged
        String room_number = roomNoCombo.getSelectedItem().toString();
        spinner.setValue(1);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
            String sql = "SELECT * FROM rooms WHERE room_no = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, room_number);
            ResultSet result = stmt.executeQuery();

            if (result.next()) {
                String roomType = result.getString("room_type");
                roomTypeTF.setText(roomType);
                String roomPrice = result.getString("room_price");
                amtTF.setText(roomPrice);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_roomNoComboItemStateChanged

    private void roomTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeTFActionPerformed

    private void roomTypeTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roomTypeTFFocusGained

    }//GEN-LAST:event_roomTypeTFFocusGained

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged

        String room_number = roomNoCombo.getSelectedItem().toString();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
            String sql = "SELECT * FROM rooms WHERE room_no = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, room_number);
            ResultSet result = stmt.executeQuery();

            if (result.next()) {

                String roomPrice = result.getString("room_price");
                int baseValue = Integer.parseInt(roomPrice);
                int days = Integer.parseInt(spinner.getValue().toString());
                int due = baseValue * days;
                amtTF.setText(String.valueOf(due));

            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_spinnerStateChanged

    private void display_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_tableMouseClicked
        int row = display_table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) display_table.getModel();
//
//        nameLabel.setText(model.getValueAt(row, 0).toString());
//        nameTF.setBackground(Color.red);
//        phoneTF.setText(model.getValueAt(row, 1).toString());
//        idTF.setText(model.getValueAt(row, 2).toString());
//        roomNoCombo.setSelectedItem(model.getValueAt(row, 3).toString());
//        roomTypeTF.setText(model.getValueAt(row, 4).toString());
//        spinner.setValue(model.getValueAt(row, 5).toString());
//        amtTF.setText(model.getValueAt(row, 6).toString());
//        paymentCombo.setSelectedItem(model.getValueAt(row, 7).toString());

    try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HC_LTD", "root", "");
           
            //UPDATING THE ROOM STATUS UPON MAKING RESERVATION
            String updateStatus = "UPDATE rooms SET room_state = ? WHERE room_no = ?";
            PreparedStatement updateStmt = conn.prepareStatement(updateStatus);
            updateStmt.setInt(1, 0);
            updateStmt.setObject(2, model.getValueAt(row, 3).toString());
            updateStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "CHECKED OUT!");
            updateCombo();

        } catch (Exception e) {
            System.out.print(e);
        }


    }//GEN-LAST:event_display_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room_reserve_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room_reserve_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room_reserve_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room_reserve_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new room_reserve_form().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amtTF;
    private javax.swing.JButton bookBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTable display_table;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTF;
    private javax.swing.JComboBox<String> paymentCombo;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton refresh;
    private javax.swing.JComboBox<String> roomNoCombo;
    private javax.swing.JTextField roomTypeTF;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
